# Generated by Django 3.2.5 on 2021-11-22 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todomodel',
            old_name='name',
            new_name='title',
        ),
        migrations.AddField(
            model_name='todomodel',
            name='content',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='todomodel',
            name='id',
            field=models.IntegerField(max_length=11, primary_key=True, serialize=False),
        ),
    ]
